# Generated by Django 2.2 on 2019-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_call', models.PositiveSmallIntegerField(choices=[(1, 'Start'), (2, 'End')])),
                ('timestamp_call', models.DateTimeField()),
                ('id_call', models.PositiveIntegerField()),
                ('source_call', models.CharField(blank=True, max_length=11, null=True)),
                ('destination_call', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Register Call',
                'verbose_name_plural': 'Register Calls',
                'unique_together': {('type_call', 'id_call'), ('type_call', 'timestamp_call'), ('type_call', 'timestamp_call', 'id_call', 'source_call', 'destination_call')},
            },
        ),
    ]
