# Generated by Django 2.2 on 2019-05-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=7, null=True)),
                ('source_call', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_call', models.CharField(max_length=11)),
                ('duration_call', models.CharField(max_length=11)),
                ('price_call', models.CharField(max_length=11)),
                ('start_date_call', models.DateField(max_length=11)),
                ('start_time_call', models.TimeField()),
                ('phone_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='phonebill.PhoneBill')),
            ],
            options={
                'ordering': ['phone_bill'],
            },
        ),
    ]
